name: CI
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    publish:
        name: Build and Deploy
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: "12.x"

            - name: Build
              run: |
                  npm install
                  npm run release

            - name: Prepare Assets
              run: cp -r ./assets ./dist/assets

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
